version: '3.9'

services:

  doctors:
    build:
      context: doctors/
      dockerfile: Dockerfile
    init: true
    deploy:
    networks:
      - mynet

  appointments:
    build:
      context: appointments/
      dockerfile: Dockerfile
    init: true
    deploy:
    networks:
      - mynet

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    init: true
    environment:
      DOCTORS_SERVICE_URL: doctors:9092
      APPOINTMENTS_SERVICE_URL: appointments:7072
    deploy:
    networks:
      - mynet
    ports:
      - "4000:3000"
    depends_on:
      - doctors
      - appointments

  db:
    image: mysql:latest
    ports:
      - 3300:3300
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./data:/var/lib/mysql

networks:
  mynet:
    driver: bridge
