version: '3.9'

services:

  doctors:
    image: rohail0463/doctors:v3.5
    networks:
      - backend_network
      - frontend_network

  appointments:
    image: rohail0463/appointments:v3.6
    networks:
      - backend_network
      - frontend_network

  frontend:
    image: rohail0463/frontend:v3.5
    ports:
      - "4000:3000" 
    depends_on:
      - doctors
      - appointments  
    networks:
      - frontend_network
    environment:
      DOCTORS_SERVICE_URL: doctors:9092
      APPOINTMENTS_SERVICE_URL: appointments:7072


  db:
    image: mysql:latest
    ports:
      - 3300:3300
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./data:/var/lib/mysql

networks:
  frontend_network:
    driver: bridge
      
  backend_network:
    driver: bridge  
    
     
