apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      containers:
      - name: appointments
        image: rohail0463/appointments:latest  
        env:
        - name: DATABASE_HOST
          value: db-service  
        - name: DATABASE_PORT
          value: "3300"
 
---        
apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  

