apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rohail0463/frontend
          ports:
            - containerPort: 3000
          env:
            - name: DOCTORS_SERVICE_URL
              value: "10.107.173.156:9092" 
            - name: APPOINTMENTS_SERVICE_URL
              value: "10.111.132.87:7072"
          resources:
            limits:
              memory: "100Mi"
              cpu: "100m"
            requests:
              memory: "100Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /api/doctors
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/doctors
              port: 3000
            initialDelaySeconds: 7
            periodSeconds: 7
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000