name: Appointments CI/CD

on:
  pull_request:
    paths:
      - 'appointments/**'
  push:
    branches:
      - main
    paths:
      - 'appointments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Version
        id: set_version
        run: echo "::set-output name=version::v3.5"

      - name: Build and Push Docker Image
        run: |
          SERVICE_NAME="appointments"
          DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${SERVICE_NAME}:${{ steps.set_version.outputs.version }}"
          echo "Building Docker Image $DOCKER_IMAGE"
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t $DOCKER_IMAGE "./$SERVICE_NAME"
          docker push $DOCKER_IMAGE

      - name: Update Docker Compose
        run: |
          SERVICE_NAME="appointments"
          DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/${SERVICE_NAME}:${{ steps.set_version.outputs.version }}"
          sed -i "s#image: ${SERVICE_NAME}.*#image: ${DOCKER_IMAGE}#" "docker-compose.yaml"

      - name: Commit and Push Changes
        run: |
          git config --global user.email "rohailzubair263@gmail.com"
          git config --global user.name "Rohail Zubair"
          git config pull.rebase false
          git add "./$SERVICE_NAME/Dockerfile"
          git add "docker-compose.yaml"
          git commit -m "Update Docker Compose file for $SERVICE_NAME with version ${{ steps.set_version.outputs.version }}"
          git pull origin main
          git push origin main
