name: Appointments CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'appointments/**'
  pull_request:
    branches:
      - '*'
    paths:
      - 'appointments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Tag
        id: set_tag
        run: echo "::set-output name=tag::v3.$((GITHUB_RUN_NUMBER))"

      - name: Build and Push Docker image
        run: |
          TAG="${{ steps.set_tag.outputs.tag }}"
          DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/appointments:${TAG}"
          echo "docker Image is $DOCKER_IMAGE"
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t $DOCKER_IMAGE ./appointments
          docker push $DOCKER_IMAGE

  update-docker-compose:
    runs-on: ubuntu-latest
    needs:
      - build-and-push
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set Tag
        id: set_tag
        run: echo "::set-output name=tag::v3.$((GITHUB_RUN_NUMBER))"

      - name: Update Docker Compose
        run: |
          TAG="${{ steps.set_tag.outputs.tag }}"
          DOCKER_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/appointments:${TAG}"
          echo "Updating Docker Compose for appointments with image $DOCKER_IMAGE"

          # Replace the image tag in the Docker Compose file
          sed -i "s#image: ${DOCKER_IMAGE}.*#image: ${DOCKER_IMAGE}#" "docker-compose.yml"

      - name: Commit and Push Changes
        run: |
          git config --global user.email "rohailzubair263@gmail.com"
          git config --global user.name "Rohail-Zubair"
          git config pull.rebase false
          git add ./docker-compose.yml
          git commit -m "Update Docker Compose file with new appointments image tags"
          git pull origin main
          git push origin main
