name: Appointments Microservice CI/CD

on:
  pull_request:
    paths:
      - 'appointments/**'
  push:
    branches: [ "main" ]
    paths:
      - 'appointments/**'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
       

    - name: Build and Push Docker Image
      run: |
        APPOINTMENTS_VERSION=$(echo "${{ github.sha }}" | cut -c1-7)
        docker docker build -t rohail0463/appointments:${APPOINTMENTS_VERSION} ./appointments
        docker push rohail0463/appointments:${APPOINTMENTS_VERSION}

  update-docker-compose:
    needs: build-and-push-image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Docker Compose
      run: |
        APPOINTMENTS_VERSION=$(echo "${{ github.sha }}" | cut -c1-7)
        sed -i "s|appointments:[0-9a-f]\+|appointments:${APPOINTMENTS_VERSION}|" docker-compose.yml

    - name: Commit and Push Changes
      run: |
       git config --global user.email "rohailzubair263@gmail.com"
       git config --global user.name "Rohail-Zubair"
       git config pull.rebase false
       git add ./docker-compose.yml
       git commit -m "Update Appointments Microservice version to ${APPOINTMENTS_VERSION}"
       git pull origin main
       git push origin main
  
